<?php defined("ABSPATH") || die("!");
function gov_language(){
	return [
		//general
		"comment_label" => "Comment",
		"recommended_series" => "Recommended Series",
		"related_episodes" => "Related Episodes",
		"wpb_get_post_views_label" => "{{count}} Views",
		"view_all_label" => "View All",
		"previous" => "Previous",
		"next" => "Next",
		"surprise_me_label" => "Surprise Me!",
		"search_auto_label" => "Search...",
		"search_placeholder_label" => "Search...",
		"search_ep_label" => "Ep",
		//home 
		"home_hot_series_update_label" => "Hot Series Update",
		"home_latest_release_label" => "Latest Release",
		"home_recommended" => "Recommendation",
		"home_blog" => "Latest Blog",
		"home_timeago_label" => " ago",
		"home_latest_release_score_label" => "score",
		"home_latest_release_stylesix" => "series",
		"home_latest_release_stylenine" => "More details here",
		//home slider
		"home_slider_trending_label" => "{{blogname}} <b>Trending</b> This Week",
		"home_slider_summary_label" => "Summary",
		//bookmark
		"bookmark_head" => "You can save a list of anime here up to {{max}} titles. The list is displayed based on the latest update date. The list of anime is saved in the browser you are currently using.",
		"bookmark_no_item" => "YOU HAVE NO BOOKMARK, NOTHING TO SHOW",
		"bookmark_disabled_notice" => "BOOKMARK FEATURE IS DISABLED",
		"delete" =>  "Delete",
		//schedule page
		"schedule_head" => "This schedule is only an estimate based on the last update last week. So it's likely that this week's episode will release sooner or it might be too late. A 'random update' schedule based on anime that has been delayed for more than 2 days.",
		"schedule_day_name_monday" => "Monday",
		"schedule_day_name_tuesday" => "Tuesday",
		"schedule_day_name_wednesday" => "Wednesday",
		"schedule_day_name_thursday" => "Thursday",
		"schedule_day_name_friday" => "Friday",
		"schedule_day_name_saturday" => "Saturday",
		"schedule_day_name_sunday" => "Sunday",
		"schedule_random_update" => "Random Update",
		"schedule_countdown_format" => "{{days}}d {{hours}}h {{minutes}}m",
		"schedule_countdown_unknown" => "??",
		"schedule_uncountable_next_episode" => "??",
		"schedule_released" => "released",
		"schedule_release_at" => "{{time}}",
		//episode single page 
		"episode_page_below_player_keywords" => "Download <b>{{episode_title}}</b>, Watch <b>{{episode_title}}</b>, don't forget to click on the like and share button. Anime <b>{{anime_title}}</b> always updated at {{blogname}}. Don't forget to watch other anime updates.",
		"episode_select_server" => "Select Video Server",
		"episode_page_expand_player" => "Expand",
		"episode_page_turn_off_light" => "Turn Off Light",
		"episode_page_turn_on_light" => "Turn On Light",
		"episode_page_download_button" => "Download",
		"episode_page_nav_prev_label" => " Prev",
		"episode_page_nav_next_label" => "Next ",
		"episode_page_nav_all_episodes_label" => "All Episodes",
		"episode_page_view_count" => "{{count}} Views",
		"episode_page_multipart_part_text" => "Part",
		"episode_page_uploaded_at_label" => "Released on",
		"episode_page_posted_by_label" => "Posted by",
		"episode_page_more_episode_label" => "More episodes",
		//series single page
		"series_info_genres_label" => "Genres",
		"series_info_season_label" => "Season",
		"series_info_network_label" => "Network",
		"series_info_posted_on_label" => "Released on",
		"series_info_status_label" => "Status",
		"series_info_studio_label" => "Studio",
		"series_info_censor_label" => "Censor",
		"series_info_released_label" => "Released",
		"series_info_duration_label" => "Duration",
		"series_info_type_label" => "Type",
		"series_info_posted_by_label" => "Posted by",
		"series_info_updated_on_label" => "Updated on",
		"series_info_country_label" => "Country",
		"series_info_total_episodes_label" => "Episodes",
		"series_info_director_label" => "Director",
		"series_info_casts_label" => "Casts",
		"series_info_synopsis_label" => "Synopsis {{title}}",
		"series_info_rating_label" => "Rating {{rating}}",
		"series_bottom_keyword_text" => '<b>Watch full episodes {{post_title}}</b>, download {{post_title}} english subbed, {{post_title}} eng sub, download {{post_title}} eng sub, stream {{post_title}} at {{sitename}}.',
		"series_new_bottom_keyword_text" => "Watch streaming <b>{{post_title}} English Subbed</b> on {{sitename}}. You can also download free {{post_title}} Eng Sub, don't forget to watch online streaming of various quality 720P 360P 240P 480P according to your connection to save internet quota, {{post_title}} on {{sitename}} MP4 MKV hardsub softsub English subbed is already contained in the video.",
		"series_warning" => "This title has been categorized as 'mature', therefore may contain intense violence, blood/gore, sexual content and/or strong language that may not be appropriate for underage viewers.",
		"series_bookmarked_by" => "Followed {{count}} people",
		"series_download_sc" => "Download {{post_title}}",
		"series_episode_list" => "Watch {{post_title}}",
		"series_gallery_label" => "Gallery {{post_title}}",
		"series_first_episode_label" => "First Episode",
		"series_new_episode_label" => "New Episode",
		"series_episode_number" => "Episode",
		"series_episode_title" => "Episode Title",
		"series_episode_date" => "Release Date",
		"series_watch_button_label" => "Watch",
		"series_info_episode_list_label" => "Episode {{episode_number}}",
		//advanced search series
		"advanced_search_series_title_label" => "Title",
		"advanced_search_series_status_label" => "Status",
		"advanced_search_series_status_all_label" => "All",
		"advanced_search_series_status_ongoing_label" => "Ongoing",
		"advanced_search_series_status_upcoming_label" => "Upcoming",
		"advanced_search_series_status_completed_label" => "Completed",
		"advanced_search_series_status_hiatus_label" => "Hiatus",
		"advanced_search_series_type_label" => "Type",
		"advanced_search_series_type_all_label" => "All",
		"advanced_search_series_sub_label" => "Sub",
		"advanced_search_series_order_by_label" => "Order by",
		"advanced_search_series_order_by_az_label" => "A-Z",
		"advanced_search_series_order_by_za_label" => "Z-A",
		"advanced_search_series_order_by_latest_update_label" => "Latest Update",
		"advanced_search_series_order_by_latest_added_label" => "Latest Added",
		"advanced_search_series_order_by_popular_label" => "Popular",
		"advanced_search_series_genre_label" => "Genre",
		"advanced_search_series_season_label" => "Season",
		"advanced_search_series_studio_label" => "Studio",
		"advanced_search_series_show_genre_label" => "Show Genre",
		"advanced_search_series_text_mode_label" => "Text Mode",
		"advanced_search_series_image_mode_label" => "Image Mode",
		"advanced_search_series_search_button_label" => "Search",
		//filter
		"filter_all_label" => "All",
		"filter_default_label" => "Default",
		"filter_tv_type" => "TV Series",
		"filter_movie_type" => "Movie",
		"filter_live_type" => "Live Action",
		"filter_ona_type" => "ONA",
		"filter_ova_type" => "OVA",
		"filter_special_type" => "Special",
		"filter_music_type" => "Music",
		"filter_sub_sub" => "Sub",
		"filter_raw_sub" => "RAW",
		"filter_dub_sub" => "Dub",
		//widget
		"widget_episode_label" => "Episode",
		"playlist_eps_label" => "Eps",
		"breadcrumb_home_label" => "Home",
		//footer
		"footer_az" => "A-Z LIST",
		"footer_az_desc" => "Searching order by alphabet name A to Z.",
		"footer_disclaimer" => "Disclaimer: This site <i>{{blogname}}</i> does not store any files on its server. All contents are provided by non-affiliated third parties.",
		//v2.1.4
		"series_episode_sub" => "Sub",
		//v2.1.6
		"box_download_server" => "Server",
		"box_download_quality" => "Quality",
		"box_download_link" => "Links",
		"box_download_download" => "Download",
		"season_episodes_label" => "episodes",
		//v2.1.7
		"series_info_fansub_label" => "Fansub",
		//v2.1.8
		"search_page_title" => "Search '{{title}}'",
		"search_page_notfound" => "Not Found",
	];
};